<?xml version="1.0"?>
<package format="3">
  <name>pfe</name>
  <version>0.0.0</version>
  <description>Mixed C++ and Python ROS 2 node demo</description>

  <maintainer email="your@email.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <exec_depend>rclpy</exec_depend>
<exec_depend>std_msgs</exec_depend>
<exec_depend>python3</exec_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
